sulu_form:
#   csrf_protection: true # requires additional changes see: https://github.com/sulu/SuluFormBundle/blob/2.4.0/Resources/doc/csrf.md
    mail:
        from: "%env(SULU_ADMIN_EMAIL)%"
        to: "%env(SULU_ADMIN_EMAIL)%"
        sender: "%env(SULU_ADMIN_EMAIL)%"
    media:
        protected: true

    dynamic_lists:
        sulu_page.page_edit_form: # view key e.g. "sulu_page.page_edit_form" for sulu pages or "sulu_article.edit_form" for sulu articles.
            form: # unique key mostly the same as the template key or a combination between template and property key.
                template: form # template key
                property: form # form property name
                type: page # the site type e.g. page, article, … (same as the content type type param)
